quarkus.flow.definitions.dir=modules/ROOT/examples/flow
quarkus.langchain4j.ollama.devservices.enabled=false

org.acme.agentic.market-data.url=http://localhost:${quarkus.http.port}/market-data/{ticker}

quarkus.scheduler.enabled=true
quarkus.scheduler.cron-type=quartz