quarkus.flow.definitions.dir=modules/ROOT/examples/flow
quarkus.langchain4j.ollama.devservices.enabled=false

org.acme.agentic.market-data.url=http://localhost:${quarkus.http.port}/market-data/{ticker}

quarkus.scheduler.enabled=true
quarkus.scheduler.cron-type=quartz

quarkus.flow.messaging.defaults-enabled=true

# 2. Tell the compiled bridge to route traffic to local memory for tests
mp.messaging.incoming.flow-in.connector=smallrye-in-memory
mp.messaging.outgoing.flow-out.connector=smallrye-in-memory