
# ----- Kubernetes
quarkus.kubernetes.namespace=default
quarkus.kubernetes.name=durable-flow-demo
quarkus.kubernetes.part-of=quarkus-flow
quarkus.kubernetes.version=0.1.0
quarkus.kubernetes.labels.app=durable-flow-demo
quarkus.kubernetes.ports.http.container-port=8080

# --- image metadata used by the generated Deployment ---
quarkus.container-image.build=true
quarkus.container-image.image=local/durable-flow-demo:latest

# Jib
quarkus.jib.base-jvm-image=registry.access.redhat.com/ubi9/openjdk-21:1.23
quarkus.jib.use-current-timestamp=true
quarkus.container-image.push=false

quarkus.kubernetes.deploy=true

# --- generate manifests for KIND ---
quarkus.kubernetes.deployment-target=kind
quarkus.kubernetes.image-pull-policy=IfNotPresent
quarkus.kubernetes.replicas=3
quarkus.kubernetes.service-account=durable-flow-demo

quarkus.kubernetes-client.generate-rbac=true
quarkus.kubernetes.rbac.service-accounts.durable-flow-demo.use-as-default=true

quarkus.kubernetes.rbac.roles.durable-flow-demo.policy-rules.0.api-groups=
quarkus.kubernetes.rbac.roles.durable-flow-demo.policy-rules.0.resources=pods
quarkus.kubernetes.rbac.roles.durable-flow-demo.policy-rules.0.verbs=get

quarkus.kubernetes.rbac.roles.durable-flow-demo.policy-rules.1.api-groups=coordination.k8s.io
quarkus.kubernetes.rbac.roles.durable-flow-demo.policy-rules.1.resources=leases
quarkus.kubernetes.rbac.roles.durable-flow-demo.policy-rules.1.verbs=get,list,watch,create,update,patch,delete

quarkus.kubernetes.rbac.roles.durable-flow-demo.policy-rules.2.api-groups=apps
quarkus.kubernetes.rbac.roles.durable-flow-demo.policy-rules.2.resources=deployments,replicasets
quarkus.kubernetes.rbac.roles.durable-flow-demo.policy-rules.2.verbs=get,list,watch

quarkus.kubernetes.rbac.role-bindings.durable-flow-demo.subjects.durable-flow-demo.kind=ServiceAccount
quarkus.kubernetes.rbac.role-bindings.durable-flow-demo.subjects.durable-flow-demo.namespace=default
quarkus.kubernetes.rbac.role-bindings.durable-flow-demo.role-name=durable-flow-demo

# Downward API -> env vars (required by Quarkus Flow Durable k8s)
quarkus.kubernetes.env.fields.POD_NAME=metadata.name
quarkus.kubernetes.env.fields.POD_NAMESPACE=metadata.namespace

# we don't need ServiceMonitor since Prometheus operator is not installed
quarkus.kubernetes.prometheus.generate-service-monitor=false

# configMap for our infra connection
quarkus.kubernetes.env.configmaps=infra-config
