quarkus.http.port=8080
quarkus.log.category."io.quarkiverse.flow".level=DEBUG
quarkus.flow.tracing.enabled=true

quarkus.flow.durable.kube.pool.name=durable-flow

org.acme.flow.durable.kube.sleep-seconds=30
org.acme.flow.durable.kube.service-host=http://localhost:8080