# The authorization server is mocked with WireMock, so no Keycloak Dev Services container is needed.
quarkus.keycloak.devservices.enabled=false
quarkus.oidc-client.devservices.enabled=false

# WireMock
quarkus.wiremock.devservices.files-mapping=src/main/resources
wiremock.url=http://localhost:${quarkus.wiremock.devservices.port}

image.service.url=http://localhost:${quarkus.wiremock.devservices.port}/image-service/images
repos.service.url=http://localhost:${quarkus.wiremock.devservices.port}/repos-service/repos

# Used by UserProvidingInvalidTokenFlow and UserProvidingValidTokenFlow
tokens.valid-token=A.abc.signature
tokens.invalid-token=B.abc.signature

# secret handler: exchangeSecrets
# used by TokenExchangeGrantTypeFlow
myRealm.client-id=quarkus-flow
myRealm.client-secret=dummy-client-secret
myRealm.base-url=http://localhost:${quarkus.wiremock.devservices.port}/auth/realms/my-realm
exchangeSecrets.subjectToken=UIZD1UK23MAGJRI6BI
exchangeSecrets.actorToken=FWM17KEW9302CRI9FQ

oidcClient.client-id=quarkus-flow
oidcClient.client-secret=dummy-client-secret
oidcClient.base-url=http://localhost:${quarkus.wiremock.devservices.port}/auth/realms/test-realm/protocol/openid-connect/token

# secret handler: multiClient
# used by MultipleOAuth2ClientsFlow
joogle.service.url=${wiremock.url}/joogle
joogle.clientId=quarkus-flow
joogle.clientSecret=joogle-client-secret
joogle.baseUrl=${wiremock.url}

jahoo.service.url=${wiremock.url}/jahooo
jahoo.clientId=quarkus-flow
jahoo.clientSecret=jahoo-client-secret
jahoo.baseUrl=${wiremock.url}

# secret handler: clientCredentials
# used by ClientCredentialsFlow
clientCredentials.clientId=quarkus-flow
clientCredentials.clientSecret=dummy-client-secret
clientCredentials.baseUrl=http://localhost:${quarkus.wiremock.devservices.port}/auth/realms/test-realm/protocol/openid-connect/token

# secret handler: password-grant
# used by PasswordGrantTypeFlow
password-grant.base-url=http://localhost:${quarkus.wiremock.devservices.port}/auth/realms/password-grant-type
password-grant.client-id=client-id
password-grant.client-secret=client-secret
password-grant.username=josh
password-grant.password=josh!password

# secret handler: openapi
# used by OpenAPIWithOAuth2Flow
openapi.client-id=quarkus-flow
openapi.client-secret=dummy-client-secret
openapi.base-url=http://localhost:${quarkus.wiremock.devservices.port}/auth/realms/test-realm/protocol/openid-connect/token

# Native configuration
quarkus.native.resources.includes=openapi-oauth2.json