{
 "title": "Quarkus Flow",
 "description": "Quarkus Flow Dashboards",
 "tags": [
  "Quarkus",
  "Quarkus Flow",
  "Micrometer",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Workflow Instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "quarkus_flow_instance_running", "legendFormat": "{{workflow}}" }
   ]
  },
  {
   "title": "Suspended Workflow Instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quarkus_flow_instance_suspended",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Waiting Workflow Instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "quarkus_flow_instance_waiting", "legendFormat": "{{workflow}}" }
   ]
  },
  { "title": "Workflow Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average Workflow Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (workflow) (\n  rate(quarkus_flow_workflow_duration_seconds_sum[5m])\n)\n/\nsum by (workflow) (\n  rate(quarkus_flow_workflow_duration_seconds_count[5m])\n)\n",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Recent Maximum Workflow Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (workflow) (\n  quarkus_flow_workflow_duration_seconds_max\n)\n",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Workflow Execution Time (p95)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, workflow) (\n    rate(quarkus_flow_workflow_duration_seconds_bucket[5m])\n  )\n)\n",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  { "title": "Workflows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Wokflows: Started Total",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quarkus_flow_workflow_started_total",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Workflows: Completed Total",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quarkus_flow_workflow_completed_total",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Workflows: Faulted Total",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "quarkus_flow_task_failed_total", "legendFormat": "{{workflow}}" }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Task Started Total",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quarkus_flow_task_started_total",
     "legendFormat": "{{workflow}}: {{task}}"
    }
   ]
  },
  {
   "title": "Task Completed Total",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quarkus_flow_task_completed_total",
     "legendFormat": "{{workflow}}: {{task}}"
    }
   ]
  },
  {
   "title": "Task Faulted Total",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "quarkus_flow_task_failed_total", "legendFormat": "{{workflow}}: {{task}}" }
   ]
  },
  {
   "title": "Task Retries Total",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quarkus_flow_task_retries_total",
     "legendFormat": "{{workflow}}: {{task}}"
    }
   ]
  }
 ]
}