= Use JPA persistence
:page-role: howto
include::includes/attributes.adoc[]

*Quarkus Flow JPA* provides workflow restoration capabilities by storing workflow instance state using a relational database compliant with JPA. 

When active, every time a task is completed the workflow current information is written into the relational database. 
When after a server shutdown, the same application (as identified by its application id) is restored in a different Java Virtual machine, all running workflow instances resume execution at the latest recorded point. 

Automatic restoration can be disabled by setting `quarkus.flow.persistence.autoRestore` to false.

== Setup

Setup a Quarkus application with xref:getting-started.adoc[Quarkus Flow set up].

Add Quarkus Flow JPA dependency to your `pom.xml`

----
<dependency>
  <groupId>io.quarkiverse.flow</groupId>
  <artifactId>quarkus-flow-jpa</artifactId>
</dependency>
----

Setup Quarkus JDBC driver and data source to be used as per link:https://quarkus.io/guides/datasource#configure-datasources[Quarkus configure datasources]

include::includes/marshaller.adoc[]

== See also
- link:https://github.com/serverlessworkflow/sdk-java/tree/main/impl/persistence[Serverless Workflow Java SDK Persistence]
