= Use MVStore persistence
:page-role: howto
include::includes/attributes.adoc[]

*Quarkus Flow MVStore* provides workflow restoration capabilities by storing workflow instance state using MVStore

When active, every time a task is completed the workflow status is written into a local filesytem file. 
When after a server shutdown, the same application (as identified by its application id) is restored in a different Java Virtual machine, all running workflow instances resume execution at the latest recorded point. 

Automatic restoration can be disabled by setting `quarkus.flow.persistence.autoRestore` to false.

== Setup

Setup a Quarkus application with xref:getting-started.adoc[Quarkus Flow set up].

Add Quarkus Flow MVStore dependency to your `pom.xml`

----
<dependency>
  <groupId>io.quarkiverse.flow</groupId>
  <artifactId>quarkus-flow-mvstore</artifactId>
</dependency>
----

Add `quarkus.flow.persistence.mvstore.db-path` property to application.properties.

For example
----
quarkus.flow.persistence.mvstore.db-path=$HOME/testFlowMVStore.db
----

== See also
- link:https://www.h2database.com/html/mvstore.html[MVStore homepage]
- link:https://github.com/serverlessworkflow/sdk-java/tree/main/impl/persistence[Serverless Workflow Java SDK Persistence]
