quarkus.redis.devservices.enabled=false

# Values are overridden by the QuarkusTestResource at test startup.
quarkus.redis.hosts=redis://admin:password@localhost:11222
quarkus.redis.max-pool-size=64
quarkus.redis.max-pool-waiting=512
