quarkus.hibernate-orm.schema-management.strategy=none
quarkus.flyway.enabled=true
quarkus.flyway.migrate-at-start=true


# H2 by default
quarkus.datasource.db-kind=h2
quarkus.flyway.locations=db/migration/h2

# MySQL
%mysql.quarkus.datasource.db-kind=mysql
%mysql.quarkus.flyway.locations=db/migration/mysql

# PostgreSQL
%postgresql.quarkus.datasource.db-kind=postgresql
%postgresql.quarkus.flyway.locations=db/migration/postgresql

# Oracle
%oracle.quarkus.datasource.db-kind=oracle
%oracle.quarkus.flyway.locations=db/migration/oracle
