quarkus.grpc.server.port=9000
quarkus.grpc.server.plain-text=true

quarkus.grpc.clients.flowGrpc.host=localhost
quarkus.grpc.clients.flowGrpc.port=9000
quarkus.grpc.clients.flowGrpc.plain-text=true

quarkus.http.test-port=0
