package io.quarkiverse.flow.runner.model;

import java.time.Instant;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

import io.serverlessworkflow.impl.WorkflowInstance;
import io.serverlessworkflow.impl.WorkflowModel;
import io.serverlessworkflow.impl.WorkflowStatus;

/**
 * Response payload returned by the workflow execution endpoints.
 * <p>
 * Besides the instance-level information, it carries the {@code workflowApplicationId} that identifies the
 * {@link io.serverlessworkflow.impl.WorkflowApplication} (i.e. the Runner instance) that started the workflow.
 * This allows clients and gateways to correlate an execution with the application that processed it.
 */
@Schema(name = "ExecutionResponse", description = "Result of a workflow execution request")
public record ExecutionResponse(
        @Schema(description = "Identifier of the workflow application (Runner instance) that executed the workflow. "
                + "Derived from 'quarkus.application.name' when set, otherwise generated by the engine.", examples = "quarkus-flow-runner") String workflowApplicationId,
        @Schema(description = "Unique identifier of the workflow instance", examples = "550e8400-e29b-41d4-a716-446655440000") String instanceId,
        @Schema(description = "Current status of the workflow instance") WorkflowStatus status,
        @Schema(description = "Timestamp when the workflow instance started") Instant startedAt,
        @Schema(description = "Timestamp when the workflow instance completed, or null if still running", nullable = true) Instant completedAt,
        @Schema(description = "Workflow output. Always null for asynchronous executions (wait=false)", nullable = true) Object workflowOutput) {

    public static ExecutionResponse from(String workflowApplicationId, WorkflowInstance instance) {
        return new ExecutionResponse(workflowApplicationId,
                instance.id(),
                instance.status(),
                instance.startedAt(),
                instance.completedAt(),
                null);
    }

    public static ExecutionResponse from(String workflowApplicationId, WorkflowInstance instance, WorkflowModel output) {
        return new ExecutionResponse(workflowApplicationId,
                instance.id(),
                instance.status(),
                instance.startedAt(),
                instance.completedAt(),
                output.asJavaObject());
    }

}
