# Enable quarkus-flow-messaging default consumer and publisher beans
quarkus.flow.messaging.defaults-enabled=true
quarkus.flow.messaging.lifecycle-enabled=true

# Configure channels with AMQP connector
mp.messaging.incoming.flow-in.connector=smallrye-amqp
mp.messaging.incoming.flow-in.address=flow-in

mp.messaging.outgoing.flow-out.connector=smallrye-amqp
mp.messaging.outgoing.flow-out.address=flow-out

mp.messaging.outgoing.flow-lifecycle-out.connector=smallrye-amqp
mp.messaging.outgoing.flow-lifecycle-out.address=flow-lifecycle-out
